### ISSUE TITLE
Can't start the server on windows

### ISSUE THREAD

**Issue by idan1109** [JetBrains/mcp-jetbrains#1]
On windows it doesn't start the server when launching the Claude App using latest pycharm community edition it gives the following error when running from CMD:

```
npx -y @jetbrains/mcp-proxy
Error: No working IDE endpoint found in range 63342-63352
    at findWorkingIDEEndpoint (file:///C:/Users/ap/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@jetbrains/mcp-proxy/dist/src/index.js:31:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async runServer (file:///C:/Users/ap/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@jetbrains/mcp-proxy/dist/src/index.js:100:5)
file:///C:/Users/ap/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@modelcontextprotocol/sdk/dist/shared/protocol.js:257
            throw new Error("Not connected");
                  ^

Error: Not connected
    at Server.notification (file:///C:/Users/ap/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@modelcontextprotocol/sdk/dist/shared/protocol.js:257:19)
    at findWorkingIDEEndpoint (file:///C:/Users/ap/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@jetbrains/mcp-proxy/dist/src/index.js:30:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async runServer (file:///C:/Users/ap/AppData/Local/npm-cache/_npx/216f9f7f9928524d/node_modules/@jetbrains/mcp-proxy/dist/src/index.js:100:5)

Node.js v23.4.0
```

How to find the ide endpoint port?

**Comment by idan1109** [comment]
in windows and pycharm i used a different port 63341 which allows me to flag can accept external connections, then set as envviroment variable the same port and it worked!

**Comment by FilippTrigub** [comment]
Can you please explain the solution in more detail? I am struggling at the same point.
